title: "ApexaiQ Internship Documentation"
description: "A 4-week internship documentation covering weekly tasks, projects, technical learning, implementation, challenges, and outcomes."
theme: jekyll-theme-cayman
